# Generated by Django 3.1.2 on 2022-03-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'funnel',
                'managed': False,
            },
        ),
    ]
